export const ESTADOS = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];

export const NAME_TO_UF = {
  Acre: "AC",
  Alagoas: "AL",
  Amapá: "AP",
  Amapa: "AP",
  Amazonas: "AM",
  Bahia: "BA",
  Ceará: "CE",
  Ceara: "CE",
  "Distrito Federal": "DF",
  "Espírito Santo": "ES",
  "Espirito Santo": "ES",
  Goiás: "GO",
  Goias: "GO",
  Maranhão: "MA",
  Maranhao: "MA",
  "Mato Grosso": "MT",
  "Mato Grosso do Sul": "MS",
  "Minas Gerais": "MG",
  Pará: "PA",
  Para: "PA",
  Paraíba: "PB",
  Paraiba: "PB",
  Paraná: "PR",
  Parana: "PR",
  Pernambuco: "PE",
  Piauí: "PI",
  Piaui: "PI",
  "Rio de Janeiro": "RJ",
  "Rio Grande do Norte": "RN",
  "Rio Grande do Sul": "RS",
  Rondônia: "RO",
  Rondonia: "RO",
  Roraima: "RR",
  "Santa Catarina": "SC",
  "São Paulo": "SP",
  "Sao Paulo": "SP",
  Sergipe: "SE",
  Tocantins: "TO",
};

export const REGIAO_BY_UF = {
  AC: "Norte",
  AL: "Nordeste",
  AP: "Norte",
  AM: "Norte",
  BA: "Nordeste",
  CE: "Nordeste",
  DF: "Centro-Oeste",
  ES: "Sudeste",
  GO: "Centro-Oeste",
  MA: "Nordeste",
  MT: "Centro-Oeste",
  MS: "Centro-Oeste",
  MG: "Sudeste",
  PA: "Norte",
  PB: "Nordeste",
  PR: "Sul",
  PE: "Nordeste",
  PI: "Nordeste",
  RJ: "Sudeste",
  RN: "Nordeste",
  RS: "Sul",
  RO: "Norte",
  RR: "Norte",
  SC: "Sul",
  SP: "Sudeste",
  SE: "Nordeste",
  TO: "Norte",
};
